
name: all

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  watch:
    types: [started]
  schedule:
    - cron: '0 */1 * * *'

env:
  TZ: Asia/Shanghai

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: 运行操作
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 运行脚本
        run: |
          bash ./.github/ccaeo.sh

      - name: 设置上传机器人
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: 添加上传文件
        run: |
          git add .
          git status
          git commit -m "$(date '+%Y年%m月%d日·周%u·%H点%M分%S秒.%3N毫秒')" -a
          echo "::notice::$(date '+%Y年%m月%d日·周%u·%H点%M分%S秒.%3N毫秒')"
          echo "::notice::https://cdn.jsdelivr.net/gh/some6508/all@master/cv"
          echo "::notice::https://cdn.jsdelivr.net/gh/some6508/all@master/vc"

      - name: 上传 log
        uses: actions/upload-artifact@v2
        with:
          name: ccaeo.log
          path: './.ccaeo.log'

      - name: 上传 ini
        uses: actions/upload-artifact@v2
        with:
          name: all.ini
          path: './all.ini'

      - name: 上传 cv
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: './cv'

      - name: 上传 vc
        uses: actions/upload-artifact@v2
        with:
          name: vc
          path: './vc'

      - name: 开始上传到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
